name: tcc
recipe: drupal9
domain: tcc.local.com
config:
  webroot: web
  php: "8.1"
  via: nginx:1.16
  database: mysql:5.7
  drush: 10.6.1
  xdebug: true
  config:
    vhosts: .lando/nginx/tcc.local.com
    php: .lando/php/php.ini
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web -l tcc.local.com
services:
  appserver:
    composer_version: 1.10.22
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=localhost"
